ghost:
    build: ghost
    environment: 
      - NODE_ENV=production
    volumes:
      - ghost/themes/:/var/lib/ghost/themes
      - ghost/data/:/var/lib/ghost/data

nginx:
    build: nginx
    links:
      - ghost
    ports:
      - "80:80"
